/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant": "#e2e2e7",
        "secondary-container": "#d2e2ee",
        "inverse-surface": "#2f3034",
        "on-error-container": "#93000a",
        "inverse-primary": "#a7c8ff",
        "secondary-fixed": "#d5e5f1",
        "background": "#f9f9fe",
        "secondary-fixed-dim": "#b9c9d5",
        "on-secondary-container": "#55656f",
        "surface-tint": "#3a5f94",
        "outline-variant": "#c3c6d1",
        "on-primary": "#ffffff",
        "on-tertiary-fixed": "#341100",
        "primary-fixed": "#d5e3ff",
        "outline": "#737780",
        "surface-container-high": "#e8e8ed",
        "surface-bright": "#f9f9fe",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#eeedf2",
        "surface-container-highest": "#e2e2e7",
        "on-tertiary-fixed-variant": "#723610",
        "on-background": "#1a1c1f",
        "on-surface-variant": "#43474f",
        "tertiary-container": "#592300",
        "surface-container-low": "#f4f3f8",
        "tertiary-fixed": "#ffdbca",
        "primary": "#001e40",
        "on-primary-container": "#799dd6",
        "on-tertiary-container": "#d8885c",
        "surface": "#f9f9fe",
        "on-secondary-fixed": "#0e1d26",
        "on-secondary-fixed-variant": "#3a4953",
        "primary-container": "#003366",
        "tertiary": "#381300",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "on-primary-fixed": "#001b3c",
        "on-primary-fixed-variant": "#1f477b",
        "primary-fixed-dim": "#a7c8ff",
        "error-container": "#ffdad6",
        "surface-dim": "#dad9de",
        "tertiary-fixed-dim": "#ffb690",
        "on-secondary": "#ffffff",
        "on-surface": "#1a1c1f",
        "secondary": "#51606b",
        "inverse-on-surface": "#f1f0f5"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [],
}